---
- name: pi-temperature-alerter config
  template: "src=local_settings.yml.j2 dest={{ tmp102_script_root }}/local_settings.yml"
  notify:
    - restart monitor_temp

- name: install init.d script
  template: src=init.d.j2 dest=/etc/init.d/monitor_temp owner=root group=root mode=0755

